### ISSUE TITLE
 Configuration Write Error

### ISSUE THREAD

**Issue by randallpacker** [FLUX-SE/ReaVolution#3]
[https://capture.dropbox.com/MYNdfFbW9NDJUEs4](https://capture.dropbox.com/MYNdfFbW9NDJUEs4) (screenshot link)

I am receiving a Configuration Write Error after installing Reaper in the Reavolution Folder, exactly according to the instructions. I have the latest versions of Reaper and Reavolution and I'm on Windows 10. 

I can bypass the error to use Reaper, but would like to resolve this error message. 

Thanks! 

Randall

**Comment by hugo-flux** [comment]
Hello Randal

Did you send a message to support to solve this?



From: Randall Packer ***@***.***>
Date: Sunday, December 1, 2024 at 1:47 PM
To: FLUX-SE/ReaVolution ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [FLUX-SE/ReaVolution] Configuration Write Error (Issue #3)
[EXTERNAL EMAIL]

https://capture.dropbox.com/MYNdfFbW9NDJUEs4 (screenshot link)

I am receiving a Configuration Write Error after installing Reaper in the Reavolution Folder, exactly according to the instructions. I have the latest versions of Reaper and Reavolution and I'm on Windows 10.

I can bypass the error to use Reaper, but would like to resolve this error message.

Thanks!

Randall

**Comment by hugo-flux** [comment]
Known issue, in this folder location, REAPER needs administrator rights to update its preferences. The fix is simple, REAPER need to be run as administrator. If this is, for whatever reason, not possible for the user simply move the ReaVolution folder to a place that do not require administration rights to wright files, for example the “Document” folder.

Hope this helps,
Jean-Loup

From: Larin, Hugo ***@***.***>
Date: Monday, 2 December 2024 at 05:57
To: FLUX-SE/ReaVolution ***@***.***>, FLUX-SE/ReaVolution ***@***.***>
Cc: Subscribed ***@***.***>, Pecquais, JeanLoup ***@***.***>, Support Flux ***@***.***>
Subject: Re: [EXTERNAL] [FLUX-SE/ReaVolution] Configuration Write Error (Issue #3)
Hello Randal

Did you send a message to support to solve this?



From: Randall Packer ***@***.***>
Date: Sunday, December 1, 2024 at 1:47 PM
To: FLUX-SE/ReaVolution ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [FLUX-SE/ReaVolution] Configuration Write Error (Issue #3)
[EXTERNAL EMAIL]

https://capture.dropbox.com/MYNdfFbW9NDJUEs4 (screenshot link)

I am receiving a Configuration Write Error after installing Reaper in the Reavolution Folder, exactly according to the instructions. I have the latest versions of Reaper and Reavolution and I'm on Windows 10.

I can bypass the error to use Reaper, but would like to resolve this error message.

Thanks!

Randall

**Comment by jpecquais** [comment]
Hello Randall,

It tooks me a few minute to understand that the issue you raised came from Github. So, I state above, in a mail answered to Hugo, this is a known issue. In this folder location, REAPER needs administrator rights to update its preferences. The fix is simple, REAPER need to be run as administrator. If this is, for whatever reason, not possible for the user simply move the ReaVolution folder to a place that do not require administration rights to wright files, for example the “Document” folder.

I would encourage you to contact the FLUX:: support through the FLUX:: website (flux.audio) to get a quicker support !

I will close this ticket, unless I hear bad news from you.

Best regards,
Jean-Loup

**Comment by randallpacker** [comment]
So sorry Jean-Loup for my support request in the wrong place! However it's great to get such a quick response. I'll continue here in Github since I already started this "ticket." Here are the exact steps that led to the issue: 

- I had already installed and was testing Reaper for several weeks (my usual DAW is Nuendo)
- I then installed Reavolution, located in C:/Program Files/Flux/
- I tried moving the Reaper binary into the Reavolution folder according to instructions, but was unable to properly open Reaper, which would hang following the VST loading process
- I uninstalled Reaper in order to start over again.
- I then reinstalled Reaper as an Administrator into the Reavolution folder, precisely according to the instructions
- This time Reaper scanned all the VST's, but I received the Configuration error when it opened. Reaper/Reavolution works except various settings are not being saved. 

So that's the whole story. Again, thanks so much and I look forward to your thoughts.

**Comment by jpecquais** [comment]
Hello Randall,
No problem ;) Have you tried to run the app as administrator ? (right click on the app > run as administrator)

**Comment by randallpacker** [comment]
Yes, I right clicked and ran the install as an administrator. I am going to move my question over to the Reavolution forum so others may benefit from the same kind of installation issues I am having.

**Comment by jpecquais** [comment]
Hello Randall,
Sorry my response was unclear, I was not talking about the installer app but of the app itself. Let me know if it fix the problem.

**Comment by randallpacker** [comment]
Yes, Opening Reaper in admin mode did the trick. Not sure if I need to do that every time, but I'll keep an eye on it. 

Many thanks! 

Randall
